#!/data/data/hilled.pwnterm/files/usr/bin/bash
# Version: 1.0.1
# export path for android bins/tools

export PATH=/data/data/hilled.pwnterm/files/home/.pwnterm/script:/data/data/hilled.pwnterm/files/usr/bin:/data/data/hilled.pwnterm/files/usr/sbin:/sbin:/system/bin:/system/xbin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/odm/bin:/vendor/bin:.

# unset things and readd chroot things
unset PATH
unset TMP
unset TMPDIR
unset HOME
unset LD_PRELOAD

## Combine android $PATH to kali chroot $PATH
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export USRP=/data/data/hilled.pwnterm/files/usr/bin/
export TERM=xterm-256color
export SHELL=/bin/bash
export LANG=en_US.UTF-8
export HOME=/root
export TMP=/tmp
export TMPDIR=/tmp
export USER=root
export MAIL=/var/mail/root
export LOGNAME=root
export SHLVL=root
# Lets pass a binky export here too ;)
export YOU_KNOW_WHAT=THIS_IS_KALI_LINUX_NETHUNTER_FROM_JAVA_BINKY

sleep 2
echo $cmd
sleep 2
cmd=$@

/data/data/com.offsec.nethunter/files/scripts/bin/busybox_nh chroot /data/local/nhsystem/kalifs sudo $cmd
